import { IImage } from "@/types";

export const data: IImage[] = [
  {
    id: "0",
    name: "Corporate Office Building",
    url: "https://i.ibb.co.com/zVqmzCpz/pexels-lalejand-18408665.jpg",
    category: "photo",
    likes: 120,
    shares: 45,
  },
  {
    id: "1",
    name: "Mountain Landscape Aerial View",
    url: "https://i.ibb.co.com/zVqmzCpz/pexels-lalejand-18408665.jpg",
    category: "photo",
    likes: 200,
    shares: 90,
  },
  {
    id: "2",
    name: "Abstract Business Vector Background",
    url: "https://i.ibb.co.com/zVqmzCpz/pexels-lalejand-18408665.jpg",
    category: "vector",
    likes: 80,
    shares: 25,
  },
  {
    id: "3",
    name: "Modern City Skyline at Sunset",
    url: "https://i.ibb.co.com/1YkdCRwN/pexels-bruna-fossile-183845208-28469559.jpg",
    category: "photo",
    likes: 150,
    shares: 60,
  },
  {
    id: "4",
    name: "Minimal Geometric Vector Shapes",
    url: "https://i.ibb.co.com/1YkdCRwN/pexels-bruna-fossile-183845208-28469559.jpg",
    category: "vector",
    likes: 95,
    shares: 30,
  },
  {
    id: "5",
    name: "Sunset Over Forest Hills",
    url: "https://i.ibb.co.com/1YkdCRwN/pexels-bruna-fossile-183845208-28469559.jpg",
    category: "photo",
    likes: 250,
    shares: 110,
  },
  {
    id: "6",
    name: "Creative Marketing Vector Pattern",
    url: "https://i.ibb.co.com/mrQKVZds/pexels-197092734-29767372.jpg",
    category: "vector",
    likes: 70,
    shares: 20,
  },
  {
    id: "7",
    name: "Ocean Waves at Sunrise",
    url: "https://i.ibb.co.com/tgczLhP/pexels-mahmutyilmaz20-33551085.jpg",
    category: "photo",
    likes: 300,
    shares: 150,
  },
  {
    id: "8",
    name: "Business Strategy Illustration",
    url: "https://i.ibb.co.com/1YdvdGBT/pexels-nike-ossler-828524146-33642341.jpg",
    category: "vector",
    likes: 130,
    shares: 55,
  },
  {
    id: "9",
    name: "Night Sky Full of Stars",
    url: "https://i.ibb.co.com/1YkdCRwN/pexels-bruna-fossile-183845208-28469559.jpg",
    category: "photo",
    likes: 400,
    shares: 200,
  },
];
